version: '3'
services:
  db:
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: YtY&L7.NC0K5+xU
      MYSQL_DATABASE: test_db
      MYSQL_USER: gonzalomelov17db
      MYSQL_PASSWORD: NzY(F[HFjSuk~jT
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: YtY&L7.NC0K5+xU
    ports:
      - "8080:80"
  nest-project:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    depends_on:
      - db
    links:
      - db